[msg ``0213_STOP``]
[s]> You have no reason to be here[n]right now...[n][w][e]
[s]> You should go to the mountain cabin[n]to save Marie.[n][w][e]

[msg ``1205_STOP``]
[s]> You have to gather information. [n]Try asking some of the nearby people...[n][w][e]

[msg JINJYA_ITEM_01]
[s]> ...?[n][w][e]
[s]> You found something unusual...[n][w][e]
[s]> Obtained [itemVar 3 65535 0] x 1.[n][w][e]

[msg JINJYA_ITEM_02]
[s]> ...?[n][w][e]
[s]> You found something sitting on the[n]side. It seems someone left it there...[n][w][e]
[s]> Obtained [itemVar 3 65535 0] x 1.[n][w][e]

[msg JINJYA_ITEM_03]
[s]> ...?[n][w][e]
[s]> You found something sitting on the[n]side. It seems someone left it there...[n][w][e]
[s]> Obtained [itemVar 3 65535 0] x 1.[n][w][e]

[msg MSG_JINJYA_YASHIRO]
[s]> It's a small shrine.[n][w][e]
[s]> There's a fortune box sitting there,[n]but there's nothing inside...[n][w][e]

[msg MSG_JINJYA_YASHIRO_RAIN]
[s]> It's a small shrine.[n][w][e]
[s]> There's a fortune box sitting there,[n]but there's nothing inside...[n][w][e]
[s]> It seems the fortunes are put away on[n]rainy days...[n][w][e]

[msg MSG_JINJYA_OMIKUZI_DRAW]
[s]> It's a small Naoto shrine. It looks like you[n]can draw matchmaking fortunes.[n][w][e]
[s]> It costs 200 yen. You have [var 20][n]yen on you. What should you do...?[n][w][e]

[sel SEL_JINJYA_OMIKUZI_DRAW top]
[s]Draw a fortune[e]
[s]Pray to Naoto Shirogane[e]
[s]Nothing[e]

[msg MSG_NAOTO_PRAY_THINK]
[s]> ...[n][w][e]

[msg MSG_NAOTO_PRAY_NOANSWER]
[s]> ...[n][w][e]
[s]> It seems Naoto has not answered[n]your prayers[n][w][e]

[msg MSG_NAOTO_PRAY_MESSAGE]
[s]> You have received a divine blessing![n][w][e]

[msg MSG_NAOTO_PRAY_MONEY_MESSAGE]
[s]> Naoto has bestowed upon you yen for[n]your loyalties![n][w][e]
[s]> You have received [var 21] yen![n][w][e]

[msg MSG_JINJYA_OMIKUZI_NOMON]
[s]> But you don't have enough money...[n][w][e]

[msg JINJYA_EMA]
[s]> It's an ema stand.[n][w][e]
[s]> Emas with various wishes written on[n]them are hung up here.[n][w][e]

[msg MSG_JINJYA_EMA_TEST]
[s]> Make a selection.[n][w][e]

[sel SELJINJYA_EMA_TEST top]
[s]Selection 1[e]
[s]Selection 2[e]
[s]Selection 3[e]
[s]Selection 4[e]
[s]Selection 5[e]
[s]Selection 6[e]
[s]Selection 7[e]
[s]Selection 8[e]

[msg JINJYA_MIKUZIKAKE]
[s]> There is a fortune stand.[n][w][e]
[s]> Old fortunes are tied to it.[n][w][e]